#############################################################
#
# grisp-config
#
#############################################################

GRISP_CONFIG_SOURCE =
GRISP_CONFIG_VERSION = 0.1
GRISP_CONFIG_DEPENDENCIES = host-squashfs host-erlang host-fwup host-erlang-rebar3 erlinit erlang fwup ncurses openssl rng-tools

# Exclude the path to the OTP release as it is not generated by buildroot.
# It will be append later when building the firmware update.
ROOTFS_SQUASHFS_ARGS += -e srv

$(eval $(generic-package))
