# Security-pack generation configuration for gen-secpack.sh.

SECPACK_DESCRIPTION="Kontron AL/BL i.MX8M Mini development security pack"
SECPACK_GENERATE_UPDATE_SIGNING=true
SECPACK_GENERATE_SECUREBOOT=false
